config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  get "inns/show/:id", to: "visitors#show", as: "show_inn"
  get "rooms/show/:id", to: "visitors#show_room", as: "show_room"
  get "search_inns", to: "visitors#search_inns"
  get "advanced_search_inns", to: "visitors#advanced_search_inns"

  resources :inns, only: [:show, :new, :create, :edit, :update] do
    resources :rooms, only: [:new, :create], shallow: true do
      resources :custom_prices, only: [:new, :create]
    end
  end

  resources :rooms, only: [:index, :show, :edit, :update]
  resources :custom_prices, only: [:edit, :update, :destroy]

  resources :cities, only: [:index] do
    get "search", on: :collection
  end

end

app/models/inn.rb
class Inn < ApplicationRecord
  validates :corporate_name, :brand_name, :registration_number,
            :phone_number, :contact_email, :payment_methods, presence: true
  validates :registration_number, :contact_email, uniqueness: true

  has_one :address
  accepts_nested_attributes_for :address
  belongs_to :user
  has_many :rooms

  serialize :payment_methods, JSON

  def full_description
    "#{brand_name} | #{address.city}-#{address.state}"
  end
end

app/controllers/inns_controller.rb
class InnsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_inn, only: [:show, :edit, :update, :authorize_access]
  before_action :authorize_access

  def show; end

  def new
    @inn = Inn.new
    @inn.build_address
  end

  def create
    if current_user.inn.present?
      return redirect_to current_user.inn, notice: 'Você já possui uma pousada cadastrada.'
    end

    @inn = Inn.new(inn_params)
    @inn.user = current_user

    if @inn.save
      return redirect_to @inn, notice: 'Pousada cadastrada com sucesso.'
    end

    flash.now.alert = 'Não foi possível cadastrar a pousada.'
    render :new, status: :unprocessable_entity
  end

  def edit; end

  def update
    if @inn.update(inn_params)
      return redirect_to @inn, notice: 'Pousada atualizada com sucesso.'
    end

    flash.now.notice = 'Não foi possível atualizar a pousada'
    render :edit, status: :unprocessable_entity
  end

  def authorize_access
    unless @inn.nil?
      if current_user != @inn.user
        return redirect_to root_path, alert: 'Você não possui permissão.'
      end
    end

    if current_user.account_type != "host"
      redirect_to root_path, alert: 'Você não é o dono de uma pousada.'
    end
  end

  private
  def set_inn
    begin
      @inn = Inn.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      @inn = nil
    end
  end

  def inn_params
    filtered_params = params.require(:inn).permit(
      :corporate_name,
      :brand_name,
      :registration_number,
      :phone_number,
      :contact_email,
      :pet_allowed,
      :checkin_time,
      :checkout_time,
      :description,
      :usage_policies,
      :active,
      address_attributes: [:id, :street, :district, :city, :state, :postal_code],
      payment_methods: []
    )
    filtered_params[:payment_methods] = filtered_params[:payment_methods].reject(&:empty?)
    filtered_params
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def show
    begin
      @inn = Inn.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      @inn = nil
    end

    if @inn.nil? || !@inn.active?
      return redirect_to root_path, alert: 'Pousada não existe ou se encontra inativa.'
    end

    @rooms = @inn.rooms.where(active: true)

    render :template => "visitors/inns/show"
  end

  def show_room
    begin
      @room = Room.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      @room = nil
    end

    if @room.nil? || !@room.active?
      return redirect_to root_path, alert: 'Quarto não existe ou se encontra inativo.'
    end

    render :template => "visitors/rooms/show"
  end

  def search_inns
    @query = params["query"]

    if @query.present?
      @inns = Inn.where(active: true).joins(:address)
                 .where("LOWER(inns.brand_name) LIKE ? OR LOWER(addresses.district) LIKE ? OR LOWER(addresses.city) LIKE ?",
                        "%#{@query.downcase}%", "%#{@query.downcase}%", "%#{@query.downcase}%")
                 .order("LOWER(inns.brand_name)")

      render :template => "visitors/inns/search"
    end
  end

  def advanced_search_inns
    unless params.has_key?(:button)
      return render :template => "visitors/inns/advanced_search_inns"
    end

    has_bathroom = params[:has_bathroom].present?
    has_balcony = params[:has_balcony].present?
    has_air_conditioner = params[:has_air_conditioner].present?
    has_tv = params[:has_tv].present?
    has_closet = params[:has_closet].present?
    has_safe = params[:has_safe].present?
    is_disabled_accessible = params[:is_disabled_accessible].present?

    rooms = {}
    rooms[:has_bathroom] = has_bathroom if has_bathroom
    rooms[:has_balcony] = has_balcony if has_balcony
    rooms[:has_air_conditioner] = has_air_conditioner if has_air_conditioner
    rooms[:has_tv] = has_tv if has_tv
    rooms[:has_closet] = has_closet if has_closet
    rooms[:has_safe] = has_safe if has_safe
    rooms[:is_disabled_accessible] = is_disabled_accessible if is_disabled_accessible

    @inns = Inn.where(active: true)
    @inns = @inns.where(pet_allowed: true) if params[:pet_allowed].present?

    unless rooms.empty?
      @inns = @inns.left_joins(:rooms).where(rooms: rooms).distinct.order("LOWER(inns.brand_name)")
    end

    render :template => "visitors/inns/search"
  end

end

app/views/visitors/inns/advanced_search_inns.html.erb
<div class="container w-50">
  <h2 class="text-center m-4">Escolha a(s) opções desejada(s)</h2>

  <%= form_tag(advanced_search_inns_path, method: :get) do %>
    <div class="form-check">
      <%= check_box_tag :pet_allowed, class: "form-check-input" %>
      <%= label_tag :pet_allowed, Inn.human_attribute_name("pet_allowed"), class: "form-check-label" %>
    </div>
    <div class="form-check">
      <%= check_box_tag :has_bathroom, class: "form-check-input" %>
      <%= label_tag :has_bathroom, Room.human_attribute_name("has_bathroom"), class: "form-check-label" %>
    </div>
    <div class="form-check">
      <%= check_box_tag :has_balcony, class: "form-check-input" %>
      <%= label_tag :has_balcony, Room.human_attribute_name("has_balcony"), class: "form-check-label" %>
    </div>
    <div class="form-check">
      <%= check_box_tag :has_air_conditioner, class: "form-check-input" %>
      <%= label_tag :has_air_conditioner, Room.human_attribute_name("has_air_conditioner"), class: "form-check-label" %>
    </div>
    <div class="form-check">
      <%= check_box_tag :has_tv, class: "form-check-input" %>
      <%= label_tag :has_tv, Room.human_attribute_name("has_tv"), class: "form-check-label" %>
    </div>
    <div class="form-check">
      <%= check_box_tag :has_closet, class: "form-check-input" %>
      <%= label_tag :has_closet, Room.human_attribute_name("has_closet"), class: "form-check-label" %>
    </div>
    <div class="form-check">
      <%= check_box_tag :has_safe, class: "form-check-input" %>
      <%= label_tag :has_safe, Room.human_attribute_name("has_safe"), class: "form-check-label" %>
    </div>
    <div class="form-check">
      <%= check_box_tag :is_disabled_accessible, class: "form-check-input" %>
      <%= label_tag :is_disabled_accessible, Room.human_attribute_name("is_disabled_accessible"), class: "form-check-label" %>
    </div>
    <%= button_tag 'Buscar', class: "btn btn-primary mt-3" %>
    <%= link_to 'Voltar', root_path, class: "btn btn-secondary mt-3" %>
  <% end %>
</div>

app/views/visitors/inns/search.html.erb
<div class="container w-50">
  <% if @query.nil? %>
    <h2 class="text-center m-4">Resultado da busca avançada:</h2>
  <% else %>
    <h2 class="text-center m-4">Pousadas encontradas com: <%= @query %></h2>
  <% end %>

  <% if @inns.present? %>
    <p class="fw-bold"><%= @inns.count %> <%= Inn.model_name.human(count: @inns.count).downcase %> <%= t(:found_a, count: @inns.count) %>.</p>
    <ul class="list-group">
      <% @inns.each do |inn| %>
        <li class="list-group-item">
          <%= link_to inn.brand_name, show_inn_path(inn), class: "text-decoration-none text-dark" %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p class="mt-3">Nenhum registro encontrado.</p>
  <% end %>

  <%= link_to 'Voltar', root_path, class: "btn btn-secondary mt-3" %>
</div>

app/views/visitors/inns/show.html.erb
<div class="container w-75">
  <h1 class="text-center m-4">Dados da Pousada</h1>

  <div class="row">
    <div class="col-md-4">
      <p><strong><%= Inn.human_attribute_name("brand_name") %>:</strong> <%= @inn.brand_name %></p>
    </div>
    <div class="col-md-4">
      <p><strong><%= Address.model_name.human %>: </strong><%= @inn.address.street %>, <%= @inn.address.district %>,
        <%= @inn.address.city %>-<%= @inn.address.state %>, <%= @inn.address.postal_code %></p>
    </div>
    <div class="col-md-4">
      <p><strong><%= Inn.human_attribute_name("phone_number") %>:</strong> <%= @inn.phone_number %></p>
    </div>
    <div class="col-md-4">
      <p><strong><%= Inn.human_attribute_name("contact_email") %>:</strong> <%= @inn.contact_email %></p>
    </div>
    <div class="col-md-4">
      <p><strong><%= Inn.human_attribute_name("checkin_time") %>:</strong> <%= @inn.checkin_time.strftime('%H:%M') %></p>
    </div>
    <div class="col-md-4">
      <p><strong><%= Inn.human_attribute_name("checkout_time") %>:</strong> <%= @inn.checkout_time.strftime('%H:%M') %></p>
    </div>
    <div class="col-md-4">
      <p><strong><%= Inn.human_attribute_name("pet_allowed") %>:</strong> <%= @inn.pet_allowed ? 'Sim' : 'Não' %></p>
    </div>

    <div class="col-md-4">
      <p><strong><%= PaymentMethod.model_name.human %>:</strong></p>
      <ul>
        <% @inn.payment_methods.each do |method| %>
          <li><%= PaymentMethod.human_attribute_name("method.#{method}") %></li>
        <% end %>
      </ul>
    </div>

    <div class="col-md-4">
      <p><strong><%= Inn.human_attribute_name("description") %>:</strong> <%= @inn.description %></p>
    </div>
    <div class="col-md-4">
      <p><strong><%= Inn.human_attribute_name("usage_policies") %>:</strong> <%= @inn.usage_policies %></p>
    </div>
  </div>

</div>

<div class="container w-75">
  <h2 class="text-center m-4">Quartos disponíveis</h2>
  <% if @rooms.any? %>
    <table class="table">
      <thead>
      <tr>
        <th scope="col"><%= Room.human_attribute_name("name") %></th>
        <th scope="col"><%= Room.human_attribute_name("dimension") %></th>
        <th scope="col"><%= Room.human_attribute_name("max_accommodation") %></th>
        <th scope="col">Detalhes</th>
      </tr>
      </thead>
      <tbody>
      <% @rooms.each do |room| %>
        <% if room.active? %>
          <tr>
            <td><%= room.name %></td>
            <td><%= room.dimension %>m²</td>
            <td><%= room.max_accommodation %></td>
            <td><%= link_to "Visualizar", show_room_path(room) %></td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
  <% else %>
    <p>Não há quartos disponíveis para esta pousada.</p>
  <% end %>

  <%= link_to 'Voltar', root_path, class: "btn btn-secondary mt-4" %>
</div>