config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  get "inns/show/:id", to: "visitors#show", as: "show_inn"
  get "rooms/show/:id", to: "visitors#show_room", as: "show_room"
  get "search_inns", to: "visitors#search_inns"
  get "advanced_search_inns", to: "visitors#advanced_search_inns"

  resources :inns, only: [:show, :new, :create, :edit, :update] do
    resources :rooms, only: [:new, :create], shallow: true do
      resources :custom_prices, only: [:new, :create]
    end
  end

  resources :rooms, only: [:index, :show, :edit, :update]
  resources :custom_prices, only: [:edit, :update, :destroy]

  resources :cities, only: [:index] do
    get "search", on: :collection
  end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = Inn.where(active: true).joins(:address).distinct.pluck('addresses.city')

    render :template => "visitors/cities/index"
  end

  def search
    @city = params[:city]

    if @city.present?
      @inns = Inn.where(active: true).joins(:address).where(addresses: { city: @city }).order("LOWER(inns.brand_name)")

      render :template => "visitors/cities/search"
    end
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def show
    begin
      @inn = Inn.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      @inn = nil
    end

    if @inn.nil? || !@inn.active?
      return redirect_to root_path, alert: 'Pousada não existe ou se encontra inativa.'
    end

    @rooms = @inn.rooms.where(active: true)

    render :template => "visitors/inns/show"
  end

  def show_room
    begin
      @room = Room.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      @room = nil
    end

    if @room.nil? || !@room.active?
      return redirect_to root_path, alert: 'Quarto não existe ou se encontra inativo.'
    end

    render :template => "visitors/rooms/show"
  end

  def search_inns
    @query = params["query"]

    if @query.present?
      @inns = Inn.where(active: true).joins(:address)
                 .where("LOWER(inns.brand_name) LIKE ? OR LOWER(addresses.district) LIKE ? OR LOWER(addresses.city) LIKE ?",
                        "%#{@query.downcase}%", "%#{@query.downcase}%", "%#{@query.downcase}%")
                 .order("LOWER(inns.brand_name)")

      render :template => "visitors/inns/search"
    end
  end

  def advanced_search_inns
    unless params.has_key?(:button)
      return render :template => "visitors/inns/advanced_search_inns"
    end

    has_bathroom = params[:has_bathroom].present?
    has_balcony = params[:has_balcony].present?
    has_air_conditioner = params[:has_air_conditioner].present?
    has_tv = params[:has_tv].present?
    has_closet = params[:has_closet].present?
    has_safe = params[:has_safe].present?
    is_disabled_accessible = params[:is_disabled_accessible].present?

    rooms = {}
    rooms[:has_bathroom] = has_bathroom if has_bathroom
    rooms[:has_balcony] = has_balcony if has_balcony
    rooms[:has_air_conditioner] = has_air_conditioner if has_air_conditioner
    rooms[:has_tv] = has_tv if has_tv
    rooms[:has_closet] = has_closet if has_closet
    rooms[:has_safe] = has_safe if has_safe
    rooms[:is_disabled_accessible] = is_disabled_accessible if is_disabled_accessible

    @inns = Inn.where(active: true)
    @inns = @inns.where(pet_allowed: true) if params[:pet_allowed].present?

    unless rooms.empty?
      @inns = @inns.left_joins(:rooms).where(rooms: rooms).distinct.order("LOWER(inns.brand_name)")
    end

    render :template => "visitors/inns/search"
  end

end

app/views/visitors/cities/index.html.erb
<div class="container w-50">
  <h1 class="text-center m-4">Lista de cidades</h1>
  <ul class="list-group">
    <% @cities.each do |city| %>
      <li class="list-group-item">
        <%= link_to city, search_cities_path(city: city), class: "text-decoration-none text-dark" %>
      </li>
    <% end %>
  </ul>

  <%= link_to 'Voltar', root_path, class: "btn btn-secondary mt-3" %>
</div>

app/views/visitors/cities/search.html.erb
<div class="container w-50">
  <h2 class="text-center m-4">Pousadas encontradas na cidade: <%= @city %></h2>

  <% if @inns.present? %>
    <p class="fw-bold"><%= @inns.count %> <%= Inn.model_name.human(count: @inns.count).downcase %> <%= t(:found_a, count: @inns.count) %>.</p>
    <ul class="list-group">
      <% @inns.each do |inn| %>
        <li class="list-group-item">
          <%= link_to inn.brand_name, show_inn_path(inn), class: "text-decoration-none text-dark" %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>Nenhum registro encontrado.</p>
  <% end %>

  <%= link_to 'Voltar', cities_path, class: "btn btn-secondary mt-3" %>
</div>