config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  get "inns/show/:id", to: "visitors#show", as: "show_inn"
  get "rooms/show/:id", to: "visitors#show_room", as: "show_room"
  get "search_inns", to: "visitors#search_inns"
  get "advanced_search_inns", to: "visitors#advanced_search_inns"

  resources :inns, only: [:show, :new, :create, :edit, :update] do
    resources :rooms, only: [:new, :create], shallow: true do
      resources :custom_prices, only: [:new, :create]
    end
  end

  resources :rooms, only: [:index, :show, :edit, :update]
  resources :custom_prices, only: [:edit, :update, :destroy]

  resources :cities, only: [:index] do
    get "search", on: :collection
  end

end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, :dimension, :standard_price, presence: true

  belongs_to :inn
  has_many :custom_prices
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room, only: [:show, :edit, :update, :authorize_access]
  before_action :check_room, only: [:show, :edit, :update]
  before_action :authorize_access, only: [:edit, :update, :new, :create]

  def index
    @rooms = current_user.inn.rooms
  end

  def show
    @custom_prices = @room.custom_prices
  end

  def new
    @room = Room.new
    @inn = current_user.inn
  end

  def create
    @room = current_user.inn.rooms.build(room_params)

    if @room.save
      return redirect_to room_path(@room), notice: 'Quarto cadastrado com sucesso.'
    end

    flash.now.alert = 'Não foi possível cadastrar o quarto.'
    render :new, status: :unprocessable_entity
  end

  def edit; end

  def update
    if @room.update(room_params)
      return redirect_to room_path(@room), notice: 'Quarto atualizado com sucesso.'
    end

    flash.now.notice = 'Não foi possível atualizar o quarto.'
    render :edit, status: :unprocessable_entity
  end

  def authorize_access
    unless @room.nil?
      if current_user != @room.inn.user
        return redirect_to root_path, alert: 'Você não possui permissão.'
      end
    end

    if current_user.account_type != "host"
      redirect_to root_path, alert: 'Você não é o dono de uma pousada.'
    end
  end

  def check_room
    if @room.nil?
      redirect_to root_path, alert: 'Esse quarto não existe.'
    end
  end

  private

  def set_room
    @inn = current_user.inn
    begin
      @room = Room.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      @room = nil
    end
  end

  def room_params
    params.require(:room).permit(
      :name,
      :description,
      :dimension,
      :max_accommodation,
      :standard_price,
      :has_bathroom,
      :has_balcony,
      :has_air_conditioner,
      :has_tv,
      :has_closet,
      :has_safe,
      :is_disabled_accessible,
      :active
    )
  end
end

app/views/rooms/edit.html.erb
<h1 class="text-center m-4">Editar quarto</h1>

<div class="container w-75">
  <% if @room.errors.any? %>
    <div class="alert alert-danger">
      <p>Verifique os erros abaixo:</p>
      <ul>
        <% @room.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with model: @room, html: { class: "row g-3 mx-auto" } do |f| %>
    <div class="col-md-6">
      <%= f.label :name, class: "form-check-label" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="col-md-6">
      <%= f.label :dimension, class: "form-check-label" %>
      <%= f.number_field :dimension, class: "form-control" %>
    </div>
    <div class="col-md-6">
      <%= f.label :max_accommodation, class: "form-check-label" %>
      <%= f.number_field :max_accommodation, class: "form-control" %>
    </div>
    <div class="col-md-6">
      <%= f.label :standard_price, class: "form-check-label" %>
      <%= f.number_field :standard_price, class: "form-control" %>
    </div>
    <div class="col-md-12">
      <%= f.label :description, class: "form-check-label" %>
      <%= f.text_area :description, class: "form-control" %>
    </div>
    <div class="d-flex col-md-3">
      <%= f.label :has_bathroom, class: "form-check-label" %>
      <div class="form-switch ms-2">
        <%= f.check_box :has_bathroom, class: "form-check-input" %>
      </div>
    </div>
    <div class="d-flex col-md-3">
      <%= f.label :has_balcony, class: "form-check-label" %>
      <div class="form-switch ms-2">
        <%= f.check_box :has_balcony, class: "form-check-input" %>
      </div>
    </div>
    <div class="d-flex col-md-3">
      <%= f.label :has_air_conditioner, class: "form-check-label" %>
      <div class="form-switch ms-2">
        <%= f.check_box :has_air_conditioner, class: "form-check-input" %>
      </div>
    </div>
    <div class="d-flex col-md-3">
      <%= f.label :has_tv, class: "form-check-label" %>
      <div class="form-switch ms-2">
        <%= f.check_box :has_tv, class: "form-check-input" %>
      </div>
    </div>
    <div class="d-flex col-md-3">
      <%= f.label :has_closet, class: "form-check-label" %>
      <div class="form-switch ms-2">
        <%= f.check_box :has_closet, class: "form-check-input" %>
      </div>
    </div>
    <div class="d-flex col-md-3">
      <%= f.label :has_safe, class: "form-check-label" %>
      <div class="form-switch ms-2">
        <%= f.check_box :has_safe, class: "form-check-input" %>
      </div>
    </div>
    <div class="d-flex col-md-3">
      <%= f.label :is_disabled_accessible, class: "form-check-label" %>
      <div class="form-switch ms-2">
        <%= f.check_box :is_disabled_accessible, class: "form-check-input" %>
      </div>
    </div>
    <div class="d-flex col-md-3">
      <% if @room.valid? %>
        <%= f.label :active, class: "form-check-label" %>
        <div class="form-switch ms-2">
          <%= f.check_box :active, class: "form-check-input" %>
        </div>
      <% end %>
    </div>
    <div class="actions">
      <%= f.submit 'Salvar', class: "btn btn-success" %>
      <%= link_to 'Voltar', rooms_path, class: "btn btn-secondary" %>
    </div>
  <% end %>
</div>

app/views/rooms/index.html.erb
<div class="container mt-4">
  <h1 class="mb-2">Meus quartos</h1>
  <%= link_to 'Cadastrar novo quarto', new_inn_room_path(current_user.inn), class: "btn btn-primary mb-4" %>

  <h2>Lista de Quartos</h2>

  <% if @rooms.any? %>
    <table class="table">
      <thead>
      <tr>
        <th>Nome</th>
        <th>Descrição</th>
        <th>Dimensão</th>
        <th>Preço padrão</th>
        <th>Status</th>
        <th>Ação</th>
      </tr>
      </thead>
      <tbody>
      <% @rooms.each do |room| %>
        <tr>
          <td><%= room.name %></td>
          <td><%= room.description %></td>
          <td><%= room.dimension %>m2</td>
          <td><%= number_to_currency(room.standard_price, unit: "R$") %></td>
          <td><%= room.active ? 'Ativo' : 'Inativo' %></td>
          <td>
            <%= link_to 'Detalhes', room_path(room), class: "btn btn-info btn-sm" %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% else %>
    <p class="mt-3">Não há quartos cadastrados para esta pousada.</p>
  <% end %>
</div>

app/views/rooms/new.html.erb
<h1 class="text-center m-4">Cadastrar novo quarto</h1>

<div class="container w-75">
  <% if @room.errors.any? %>
    <div class="alert alert-danger">
      <p>Verifique os erros abaixo:</p>
      <ul>
        <% @room.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for [@inn, @room], html: { class: "row g-3 mx-auto" } do |f| %>
    <div class="col-md-6">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="col-md-6">
      <%= f.label :dimension %>
      <%= f.number_field :dimension, class: "form-control" %>
    </div>
    <div class="col-md-6">
      <%= f.label :max_accommodation %>
      <%= f.number_field :max_accommodation, class: "form-control" %>
    </div>
    <div class="col-md-6">
      <%= f.label :standard_price %>
      <%= f.number_field :standard_price, class: "form-control" %>
    </div>
    <div class="col-md-12">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>
    </div>
    <div class="d-flex col-md-3">
      <%= f.label :has_bathroom, class: "form-check-label" %>
      <div class="form-switch ms-2">
        <%= f.check_box :has_bathroom, class: "form-check-input" %>
      </div>
    </div>
    <div class="d-flex col-md-3">
      <%= f.label :has_balcony, class: "form-check-label" %>
      <div class="form-switch ms-2">
        <%= f.check_box :has_balcony, class: "form-check-input" %>
      </div>
    </div>
    <div class="d-flex col-md-3">
      <%= f.label :has_air_conditioner, class: "form-check-label" %>
      <div class="form-switch ms-2">
        <%= f.check_box :has_air_conditioner, class: "form-check-input" %>
      </div>
    </div>
    <div class="d-flex col-md-3">
      <%= f.label :has_tv, class: "form-check-label" %>
      <div class="form-switch ms-2">
        <%= f.check_box :has_tv, class: "form-check-input" %>
      </div>
    </div>
    <div class="d-flex col-md-3">
      <%= f.label :has_closet, class: "form-check-label" %>
      <div class="form-switch ms-2">
        <%= f.check_box :has_closet, class: "form-check-input" %>
      </div>
    </div>
    <div class="d-flex col-md-3">
      <%= f.label :has_safe, class: "form-check-label" %>
      <div class="form-switch ms-2">
        <%= f.check_box :has_safe, class: "form-check-input" %>
      </div>
    </div>
    <div class="d-flex col-md-3">
      <%= f.label :is_disabled_accessible, class: "form-check-label" %>
      <div class="form-switch ms-2">
        <%= f.check_box :is_disabled_accessible, class: "form-check-input" %>
      </div>
    </div>
    <div class="d-flex col-md-3">
      <% if @room.valid? %>
        <%= f.label :active, class: "form-check-label" %>
        <div class="form-switch ms-2">
          <%= f.check_box :active, class: "form-check-input" %>
        </div>
      <% end %>
    </div>
    <div class="actions">
      <%= f.submit 'Salvar', class: "btn btn-success" %>
      <%= link_to 'Voltar', rooms_path, class: "btn btn-secondary" %>
    </div>
  <% end %>
</div>

app/views/rooms/show.html.erb
<div class="container w-75">
  <h1 class="text-center m-4">Detalhes do quarto</h1>

  <div class="row">
    <div class="col-md-4">
      <p><strong>Status:</strong> <%= @room.active ? 'Ativo' : 'Inativo' %></p>
    </div>
    <div class="col-md-4">
      <p><strong><%= Room.human_attribute_name("name") %>: </strong> <%= @room.name %></p>
    </div>
    <div class="col-md-4">
      <p><strong><%= Room.human_attribute_name("dimension") %>: </strong> <%= @room.dimension %>m²</p>
    </div>
    <div class="col-md-4">
      <p><strong><%= Room.human_attribute_name("max_accommodation") %>: </strong> <%= @room.max_accommodation %></p>
    </div>
    <div class="col-md-4">
      <p><strong><%= Room.human_attribute_name("standard_price") %>: </strong><%= number_to_currency(@room.standard_price, :unit => "R$") %></p>
    </div>
    <div class="col-md-4">
      <p><strong><%= Room.human_attribute_name("has_bathroom") %>: </strong> <%= @room.has_bathroom ? 'Sim' : 'Não' %>
      </p>
    </div>
    <div class="col-md-4">
      <p><strong><%= Room.human_attribute_name("has_balcony") %>: </strong> <%= @room.has_balcony ? 'Sim' : 'Não' %></p>
    </div>
    <div class="col-md-4">
      <p><strong><%= Room.human_attribute_name("has_air_conditioner") %>
        :</strong> <%= @room.has_air_conditioner ? 'Sim' : 'Não' %></p>
    </div>
    <div class="col-md-4">
      <p><strong><%= Room.human_attribute_name("has_tv") %>: </strong> <%= @room.has_tv ? 'Sim' : 'Não' %></p>
    </div>
    <div class="col-md-4">
      <p><strong><%= Room.human_attribute_name("has_closet") %>: </strong> <%= @room.has_closet ? 'Sim' : 'Não' %></p>
    </div>
    <div class="col-md-4">
      <p><strong><%= Room.human_attribute_name("has_safe") %>: </strong> <%= @room.has_safe ? 'Sim' : 'Não' %></p>
    </div>
    <div class="col-md-4">
      <p><strong><%= Room.human_attribute_name("is_disabled_accessible") %>: </strong> <%= @room.is_disabled_accessible ? 'Sim' : 'Não' %></p>
    </div>
  </div>
    <div class="col-md-4">
      <p><strong><%= Room.human_attribute_name("description") %>: </strong></p>
    </div>
    <%= link_to 'Editar', edit_room_path(@room), class: "btn btn-warning mt-3" %>

  <h2 class="text-center m-4"><%= CustomPrice.model_name.human %></h2>
  <% if @custom_prices.any? %>
    <table class="table table-bordered mt-3">
      <thead>
      <tr>
        <th>Data de início</th>
        <th>Data final</th>
        <th>Preço</th>
        <th colspan="2">Ações</th>
      </tr>
      </thead>
      <tbody>
      <% @custom_prices.each do |custom_price| %>
        <tr>
          <td><%= custom_price.start_date.strftime("%d/%m/%Y") %></td>
          <td><%= custom_price.end_date.strftime("%d/%m/%Y") %></td>
          <td><%= number_to_currency(custom_price.price, :unit => "R$") %></td>
          <td><%= link_to "Editar", edit_custom_price_path(custom_price), class: "btn btn-warning btn-sm" %></td>
          <td><%= button_to("Remover", custom_price_path(custom_price), method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn btn-danger btn-sm") %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% else %>
    <p>Não há um período de preços cadastrado para este quarto.</p>
  <% end %>

  <%= link_to 'Criar período de preços', new_room_custom_price_path(@room), class: "btn btn-primary mt-3" %>
  <%= link_to 'Voltar', rooms_path, class: "btn btn-secondary mt-3" %>
</div>