config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  get "inns/show/:id", to: "visitors#show", as: "show_inn"
  get "rooms/show/:id", to: "visitors#show_room", as: "show_room"
  get "search_inns", to: "visitors#search_inns"
  get "advanced_search_inns", to: "visitors#advanced_search_inns"

  resources :inns, only: [:show, :new, :create, :edit, :update] do
    resources :rooms, only: [:new, :create], shallow: true do
      resources :custom_prices, only: [:new, :create]
    end
  end

  resources :rooms, only: [:index, :show, :edit, :update]
  resources :custom_prices, only: [:edit, :update, :destroy]

  resources :cities, only: [:index] do
    get "search", on: :collection
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InnApp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>
<header>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container">
      <%= link_to 'Página inicial', root_path, class: "navbar-brand" %>
      <div class="collapse navbar-collapse mr-auto" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to 'Cidades', cities_path, class: "nav-link active" %>
          </li>
        </ul>

        <div class="d-flex justify-content-end">
          <%= form_with url: search_inns_path, method: :get, html: { class: "mx-auto" } do |f| %>
            <div class="input-group">
              <%= f.text_field :query, placeholder: 'Buscar pousada', class: "form-control" %>
              <%= f.submit 'Buscar', class: "btn btn-outline-success" %>
              <%= link_to 'Busca avançada', advanced_search_inns_path, class: "btn btn-outline-success" %>
            </div>
          <% end %>
        </div>

        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= current_user.email %>
              </a>
              <ul class="dropdown-menu">
                <% if current_user.inn.present? && current_user.inn.valid? %>
                  <li class="dropdown-item">
                    <%= link_to 'Minha pousada', inn_path(current_user.inn.id), class: "nav-link active" %>
                  </li>
                  <li class="dropdown-item">
                    <%= link_to 'Meus quartos', rooms_path, class: "nav-link active" %>
                  </li>
                <% end %>
                <li>
                  <hr class="dropdown-divider">
                </li>
                <li>
                  <%= button_to 'Sair', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Entrar como Anfitrião', new_user_session_path, class: "nav-link active" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>
<main>
  <div class="container">
    <div>
      <%= notice %>
      <%= alert %>
    </div>
    <%= yield %>
  </div>
</main>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
<footer>
  <div class="container p-4"></div>
</footer>
</html>